config/routes.rb
HipchatLinks::Application.routes.draw do
  devise_for :users
  resources :authors, only: :show
  resources :tags, only: [:index, :show]
  resources :favorites, only: [:create, :index, :destroy]

  get 'search', to: 'tags#show'
  resources :taggings, only: :create

  root to: 'messages#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :message
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  scope :unsent, -> { where(sent_at: nil) }
  validates :first_name, uniqueness: { scope: :last_name }, presence: true
  validates :email, uniqueness: true, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings

  scope :chronological, ->{ order(:time) }
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :messages, through: :taggings

  validates :user, presence: true
  validates :name, uniqueness: true, presence: true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
  belongs_to :message

  attr_accessor :tag_name

  validates :tag_id, uniqueness: { scope: :message_id }
  validates :tag, presence: true
  validates :message, presence: true
  validates :user, presence: true

  before_validation :make_tag, if: -> { tag.nil? }

  private

  def make_tag
    self.tag = Tag.where("name ILIKE ?", "#{tag_name}%").first ||
               Tag.create(user: user, name: tag_name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :invitation_code
  belongs_to :invite
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :invite, presence: true, uniqueness: true

  delegate :name, to: :invite

  has_many :favorites
  has_many :favorite_messages, through: :favorites, source: :message

  def invitation_code=(code)
    @invitation_code = code
    self.invite = Invite.find_by(code: code)
  end

  def messages
    Message.where(author: name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :load_message_counts
  before_action :configure_permitted_parameters, if: :devise_controller?

  def redirect_path
    @redirect_path ||= params[:redirect] || request.fullpath
  end
  helper_method :redirect_path

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :invitation_code
  end

  def load_message_counts
    @message_counts = Message.order(:week).select('week, count(*) qty').group(:week)
  end

  def after_sign_in_path_for(resource)
    params[:redirect] || super
  end

  def login_required
    unless user_signed_in?
      redirect_to new_user_session_path(redirect: redirect_path)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :login_required

  def show
    @messages = Message.where(author: params[:id]).order(:time)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :login_required

  def index
    @favorite_messages = current_user.favorite_messages.chronological
  end

  def create
    Favorite.create(params.require(:favorite).permit(:message_id).merge(user: current_user))
  end

  def destroy
    Favorite.where(message_id: params[:id], user_id: current_user.id).destroy_all
    respond_to do |format|
      format.html { redirect_to params[:redirect] }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    if params.has_key?(:week)
      @week = params.delete('week').to_i - 1
      if @week < 0 || @week > WEEK_TOPICS.count - 1
        redirect_to params
      else
        @messages = Message.where(week: @week)
      end
    end
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  before_action :login_required

  def create
    Tagging.create(tagging_params)
    respond_to do |format|
      format.json { render nothing: true }
    end
  end

  private

  def tagging_params
    params.require(:tagging).permit(:tag_name, :message_id).merge(user: current_user)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :login_required

  def index
    @tags = Tag.where("name ILIKE ?", "#{params[:term]}%").pluck(:name)
    respond_to do |format|
      format.json { render json: @tags }
    end
  end

  def show
    names = (params[:name] || params[:id]).split(/,?\s/)
    tag_query = names.map{ |name| "tags.name ILIKE ?" }.join(' OR ')
    author_query = names.map{ |name| "messages.author ILIKE ?" }.join(' OR ')
    @messages_by_tag = Message.joins(:tags).where(tag_query, *names).distinct
    @messages_by_author = Message.where(author_query, *names.map{ |name| "#{name}%"}).where.not(id: @messages_by_tag.map(&:id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def linkify(text)
    text = h(text).gsub('&quot;', '"')
    text.gsub!(/(https?:\/\/[^\s"]+)/, '<a href="\1" target="_blank">\1</a>')
    text.gsub!(/@(\w{2})\w+/, '@\1------') unless user_signed_in?
    text.sub(/^\/code\s(.*)$/, '<pre>\1</pre>').
         gsub(/\\n/, "\n").html_safe
  end
end

app/views/authors/show.html.erb
<ul class="by-author">
  <%= render @messages %>
</ul>

app/views/favorites/index.html.erb
<h1>Favorites</h1>

<ul>
  <%= render @favorite_messages %>
</ul>

app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Hip Ass Fools', root_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul>
      <li><%= link_to 'Favorites', favorites_path %></li>
    </ul>
  </section>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% unless devise_controller? %>
        <li class="has-form">
          <form action="<%= search_path %>" id="search-form">
            <div class="row collapse">
              <div class="large-10 small-9 columns">
                <input type="text" id="search" name="name" placeholder="Tag names(s) or Author first name">
              </div>
              <div class="large-2 small-3 columns">
                <input type="submit" class="button expand" value="Search" />
              </div>
            </div>
          </form>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <li class="padding-right"><%= link_to current_user.name, author_path(current_user.name) %></li>
        <li class="padding-right"><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
      <% elsif !devise_controller? %>
        <li><%= link_to 'Sign in', new_user_session_path(redirect: request.fullpath) %></li>
        <li><%= link_to 'Sign up', new_user_registration_path(redirect: request.fullpath) %></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'WDI - HipChat Messages' %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <section class="right small-12 medium-12 large-4 sidebar">
      <%= render 'shared/table_of_contents' %>
    </section>

    <section class="small-12 medium-12 large-8 main">
      <%= yield %>
    </section>


    <%= javascript_include_tag "application" %>
    <script>
      window.currentUser = <%= current_user.try(:name).to_json.html_safe %>;
    </script>
  </body>



</html>

app/views/messages/_message.html.erb
<li class="<%= cycle 'odd', 'even' %>">
  <% if user_signed_in? %>
    <span class="name large-3 small-3 medium-3 columns">
      <%= link_to message.author, author_path(message.author) %><br />
      <span class="message-date weak"> (<%= message.time.strftime('%Y-%m-%d') %>)</span>
    </span>
  <% else %>
    <span class="blur name large-3 small-3 medium-3 columns" title="Log in to access messages by names.">
      <%= link_to Faker::Name.name, '#' %>
    </span>
  <% end %>

  <span class="message-body large-7 medium-7 small-7 columns">
    <%= linkify message.body %>
    <input class="tags" id="msg<%= message.id %>" value="<%= message.tags.pluck(:name).join(',') %>" />
  </span>

  <span class="large-2 medium-2 small-2">
    <% if user_signed_in? %>
      <% if current_user.favorite_message_ids.include?(message.id) %>
        <%= link_to 'Remove favorite', favorite_path(message, redirect: request.fullpath), method: :delete, class: 'favorites-link' %>
      <% else %>
        <%= link_to 'Add to favorites', favorites_path(favorite: { message_id: message.id }), method: :post, remote: true, class: 'favorites-link', onclick: "this.style.color='gray'; this.style.cursor='text'" %>
      <% end %>
    <% end %>
  </span>
</li>

app/views/messages/index.html.erb
<% if @week %>

  <h1>Week <%= @week + 1 %> - <%= WEEK_TOPICS[@week]%></h1>

  <ul class="by-week">
    <%= render @messages %>
  </ul>
<% end %>

app/views/shared/_table_of_contents.html.erb
<h1>Table of Contents</h1>

<ul>
  <% WEEK_TOPICS.each_with_index do |topic, index| %>
    <li class="<%= 'selected' if @week == index %>">
      <span class="week-number"><%= index + 1 %>: </span>
      <span class="topic"><%= link_to topic, root_path(week: index + 1) %> </span>
      <span class="message-count weak">(<%= @message_counts[index].qty %> messages)</span>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<ul>
  <%= render @messages_by_author if @messages_by_author %>
  <%= render @messages_by_tag if @messages_by_tag %>
</ul>

<% if @messages_by_author.empty? && @messages_by_tag.empty? %>
  <h2>No results</h2>
<% end %>